### ISSUE TITLE
module not found 

### ISSUE THREAD

**Issue by prince0310** [FoundationVision/UniRef#2]
`    from detectron2.projects.ddetrs import add_ddetrs_config
ModuleNotFoundError: No module named 'detectron2.projects.ddetrs'
`

**Comment by wjn922** [comment]
Sorry for that we do not support the demo.py for visualization now. We may add a demo script in the future.

You may refer to [eval guide](https://github.com/FoundationVision/UniRef/blob/main/assets/EVALUATION.md) for evaluation on standard datasets.
