### ISSUE TITLE
model of model_final.pth

### ISSUE THREAD

**Issue by qiulesun** [FoundationVision/UniRef#6]
@wjn922 

Nice work !

Could you consider releasing the model_final.pth model pretrained on  Objects365v2 for downstream finetuning on RIS task ?

python3 projects/UniRef/train_net.py \
        --config-file projects/UniRef/configs/image/joint_task_det_rec_r50_16gpu.yaml  \
        --num-gpus=8 \
        --resume \
        OUTPUT_DIR outputs/joint_task_det_rec_r50_16gpu \
        MODEL.WEIGHTS outputs/obj365v2_r50_32gpu/**model_final.pth** \
        SOLVER.MAX_ITER 180000 \
        SOLVER.STEPS [150000,]

**Comment by wjn922** [comment]
Hi, we have updated the model links in README.
